### ISSUE TITLE
点击监控大盘自定义开始的叉号按钮后网页空白

### ISSUE THREAD

**Issue by zhangzheming629** [n9e/fe-v5#87]
前端版本:5.1.3
点击监控大盘自定义开始时间的叉号按钮或者自定义结束时间的叉号按钮后网页空白
![HEO}`) 2VI8Q1RZ5KB6UHJ](https://user-images.githubusercontent.com/38377736/154400819-43d52bcb-b518-4364-9323-479340fad770.png)

**Comment by UlricQin** [comment]
使用最新版本的Chrome进行测试。

**Comment by zhangzheming629** [comment]
你的chrome版本是多少呀，我试了chrome的Version 98.0.4758.102 (Official Build) (64-bit)这个版本还是有这个问题

**Comment by zhangzheming629** [comment]
Console里的报错如下 vendor.4a71ed37.js:27 TypeError: Cannot read properties of null (reading 'endOf')
    at vl (index.d1286030.js:1:125381)
    at $i (vendor.4a71ed37.js:27:59250)
    at ju (vendor.4a71ed37.js:27:68770)
    at Rl (vendor.4a71ed37.js:27:112504)
    at ys (vendor.4a71ed37.js:27:98712)
    at hs (vendor.4a71ed37.js:27:98640)
    at ds (vendor.4a71ed37.js:27:98503)
    at os (vendor.4a71ed37.js:27:95489)
    at vendor.4a71ed37.js:27:45129
    at e.unstable_runWithPriority (vendor.4a71ed37.js:18:3778)
Qu @ vendor.4a71ed37.js:27
Ku.n.payload @ vendor.4a71ed37.js:27
Ja @ vendor.4a71ed37.js:27
Pu @ vendor.4a71ed37.js:27
Rl @ vendor.4a71ed37.js:27
ys @ vendor.4a71ed37.js:27
hs @ vendor.4a71ed37.js:27
ds @ vendor.4a71ed37.js:27
os @ vendor.4a71ed37.js:27
(anonymous) @ vendor.4a71ed37.js:27
e.unstable_runWithPriority @ vendor.4a71ed37.js:18
Ta @ vendor.4a71ed37.js:27
za @ vendor.4a71ed37.js:27
Na @ vendor.4a71ed37.js:27
xt @ vendor.4a71ed37.js:27
Fn @ vendor.4a71ed37.js:27
index.d1286030.js:1 TypeError: Cannot read properties of null (reading 'endOf')
    at vl (index.d1286030.js:1:125381)
    at $i (vendor.4a71ed37.js:27:59250)
    at ju (vendor.4a71ed37.js:27:68770)
    at Rl (vendor.4a71ed37.js:27:112504)
    at ys (vendor.4a71ed37.js:27:98712)
    at hs (vendor.4a71ed37.js:27:98640)
    at ds (vendor.4a71ed37.js:27:98503)
    at os (vendor.4a71ed37.js:27:95489)
    at vendor.4a71ed37.js:27:45129
    at e.unstable_runWithPriority (vendor.4a71ed37.js:18:3778) 'error'
index.d1286030.js:1 TypeError: Cannot read properties of null (reading 'endOf')
    at vl (index.d1286030.js:1:125381)
    at $i (vendor.4a71ed37.js:27:59250)
    at ju (vendor.4a71ed37.js:27:68770)
    at Rl (vendor.4a71ed37.js:27:112504)
    at ys (vendor.4a71ed37.js:27:98712)
    at hs (vendor.4a71ed37.js:27:98640)
    at ds (vendor.4a71ed37.js:27:98503)
    at os (vendor.4a71ed37.js:27:95489)
    at vendor.4a71ed37.js:27:45129
    at e.unstable_runWithPriority (vendor.4a71ed37.js:18:3778) {componentStack: '\n    at vl (http://localhost:18000/assets/index.d1…ocalhost:18000/assets/index.d1286030.js:1:529011)'}

**Comment by guguji5** [comment]
@zhangzheming629 感谢反馈，代码已提交，如果着急可以自己build，不急可以等下个release
